### ISSUE TITLE
Uncaught TypeError: Cannot read property 'add' of null

### ISSUE THREAD

**Issue by jmarvdave** [inkytonik/atom-sbt#18]
[Enter steps to reproduce:]

1. Upon first installing the package and attempting to use it

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [sbt](https://github.com/inkytonik/atom-sbt) package 0.10.0

### Stack Trace

Uncaught TypeError: Cannot read property 'add' of null

```
At /Users/johndavis/.atom/packages/sbt/lib/project.coffee:49

TypeError: Cannot read property 'add' of null
    at Project.module.exports.Project.startTerm (/packages/sbt/lib/project.coffee:49:18)
    at /packages/sbt/lib/project.coffee:91:12
    at FSReqWrap.oncomplete (fs.js:123:15)
```

### Commands

```
     -8:31.9.0 window:toggle-full-screen (input.hidden-input)
  2x -8:27.5.0 application:open (input.hidden-input)
     -7:53.7.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -7:42.9.0 core:move-down (input.hidden-input)
     -7:41.8.0 core:move-up (input.hidden-input)
     -7:40.7.0 core:move-down (input.hidden-input)
     -7:40.2.0 core:confirm (input.hidden-input)
     -7:33.9.0 grammar-selector:show (atom-text-editor.editor.is-focused)
     -7:31.2.0 core:backspace (input.hidden-input)
     -6:56.4.0 settings-view:install-packages-and-themes (input.hidden-input)
     -6:46.1.0 core:confirm (input.hidden-input)
     -5:15 command-palette:toggle (input.hidden-input)
     -2:34.7.0 settings-view:install-packages-and-themes (input.hidden-input)
     -2:29.7.0 core:confirm (input.hidden-input)
     -1:40.4.0 sbt:toggle-panel (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.1 
intentions 1.1.2 
language-elm 1.5.0 
language-scala 1.1.8 
linter 2.1.4 
linter-ui-default 1.2.3 
platformio-ide-terminal 2.5.0 
sbt 0.10.0 
```

**Comment by inkytonik** [comment]
Thanks for reporting this. I think it occurs because the busy-signal package is not installed. I've pushed a commit that adds the missing dependency on that package. It will be in 0.11.0 which I hope to release soon once I've addressed a couple of other issues. In the meantime, installing the busy-signal package manually should fix this. Please let me know here.

**Comment by hawkw** [comment]
I've installed `busy-signal` and am still seeing this issue: 

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0-beta1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.11.6
**Thrown From**: [sbt](https://github.com/inkytonik/atom-sbt) package 0.11.0


### Stack Trace

Uncaught TypeError: Cannot read property 'add' of null

```
At /Users/eliza/.atom/packages/sbt/lib/project.coffee:49

TypeError: Cannot read property 'add' of null
    at Project.module.exports.Project.startTerm (/packages/sbt/lib/project.coffee:49:18)
    at /packages/sbt/lib/project.coffee:91:12
    at FSReqWrap.oncomplete (fs.js:112:15)
```

### Commands

```
     -2:54.8.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
     -0:08.8.0 command-palette:toggle (input.hidden-input)
  5x -0:07.0 core:backspace (input.hidden-input)
     -0:04.1.0 core:move-down (input.hidden-input)
     -0:03.8.0 core:confirm (input.hidden-input)
     -0:03.8.0 sbt:toggle-panel (input.hidden-input)
```

### Non-Core Packages

```
assign-align 0.1.0 
atom-beautify 0.30.3 
atom-ctags 5.1.0 
atom-language-rust 0.12.1 
atom-live-grammar-reload 0.8.0 
atom-space-race 0.2.1 
atom-space-race-syntax 0.2.0 
autocomplete-bibtex 0.7.0 
autocomplete-clang 0.11.3 
autocomplete-haskell 0.7.2 
base16-ocean-dark-spacegray 0.13.0 
base16-ocean-dark-spacegray-lighter-invisibles 0.3.0 
beacon-ui 0.5.0 
brilliance-white-theme 1.0.0 
build 0.68.0 
build-cargo 2.0.0 
build-gradle 0.6.0 
build-make 0.13.0 
build-sbt 0.6.0 
busy 0.7.0 
busy-signal 1.4.3 
cargo-test-runner 0.1.0 
Clean2 0.16.0 
clojure-eval-in-repl 1.1.0 
color-picker 2.2.5 
dash 1.7.1 
docblockr 0.10.5 
editorconfig 2.2.2 
fairyfloss 0.2.0 
file-icons 2.1.8 
fizzy 0.21.0 
gist-it 0.9.2 
git-plus 7.9.3 
git-time-machine 1.5.9 
gitignore-snippets 0.2.5 
gradle-ci 1.1.4 
haskell-ghc-mod 1.19.9 
haskell-pointfree 0.2.0 
Hydrogen 1.18.0 
ide-haskell 1.9.6 
ide-haskell-cabal 1.9.2 
ide-haskell-repl 0.6.0 
intentions 1.1.2 
isotope-ui 2.8.5 
jekyll 2.1.0 
lambda-syntax 0.5.2 
lambda-ui 1.0.4 
language-arduino 0.4.3 
language-arm 1.2.2 
language-cmake 0.3.0 
language-docker 1.1.8 
language-elm 1.5.0 
language-gdb 0.3.6 
language-gfm2 0.92.2 
language-gitignore 0.3.0 
language-glsl 2.0.1 
language-gradle 0.0.3 
language-groovy 0.7.0 
language-haskell 1.12.1 
language-hcl 0.4.0 
language-hlsl 1.2.0 
language-ini 1.19.0 
language-latex 1.0.0 
language-lisp 0.2.0 
language-purescript 0.8.2 
language-r 0.4.1 
language-rust 0.4.10 
language-scala 1.1.8 
language-scheme 1.4.0 
language-swift-3 0.4.0 
language-x86-64-assembly 2.2.11 
latex 0.44.0 
latexer 0.3.0 
linter 2.2.0 
linter-chktex 1.3.1 
linter-clojure 1.1.3 
linter-docker 0.2.0 
linter-eslint 8.2.1 
linter-gcc 0.7.1 
linter-hlint 1.0.1 
linter-javac 1.9.4 
linter-pep8 1.3.2 
linter-pycodestyle 2.0.2 
linter-rust 0.8.0 
linter-scalac 1.4.4 
linter-scalastyle 1.4.1 
linter-ui-default 1.6.2 
linter-write-good 0.9.0 
lucid-syntax 0.1.2 
mac-fix-path 0.0.0 
markdown-pdf 1.5.4 
markdown-preview-enhanced 0.13.0 
markdown-preview-katex 0.3.4 
markdown-preview-opener 0.1.1 
markdown-writer 2.6.5 
material-ui 1.0.10 
merge-conflicts 1.4.5 
minimap 4.28.2 
muted 0.1.4 
native-ui 0.21.0 
nrepl 0.4.0 
open-in-github-app 0.2.6 
open-terminal-here 2.3.0 
paredit 1.0.0 
pdf-view 0.59.0 
pigments 0.39.1 
platformio-ide 2.0.0-beta.7 
platformio-ide-debugger 1.2.3 
platformio-ide-terminal 2.5.1 
predawn-syntax 1.0.4 
predawn-ui 1.0.7 
processing 0.13.0 
processing-language 0.2.0 
project-manager 3.3.5 
project-quick-open 0.5.0 
r-exec 0.5.0 
racer 0.20.0 
regex-railroad-diagram 0.19.3 
rust-api-docs-helper 0.5.1 
sbt 0.11.0 
scala-format 0.1.8 
scala-worksheet 0.3.4 
scala-worksheet-plus 0.4.2 
script 3.15.0 
shiny-ui 0.36.0 
slack-ui 0.8.0 
spacegray-black-syntax 0.1.4 
spacegray-dark-syntax 0.2.0 
spacegray-dark-ui 0.13.0 
spacegray-eighties-dark-syntax 0.6.2 
spacegray-eighties-ui 2.0.0 
spacegray-light-syntax 0.1.0 
spacegray-light-ui 0.1.0 
symbols-tree-view 0.14.0 
tablr 1.8.3 
tabs-to-spaces 1.0.3 
tidy-markdown 3.0.1 
todo-show 1.11.0 
tokamak 0.3.2 
tokamak-terminal 10.0.1 
tool-bar 1.1.0 
tool-bar-atom 1.7.0 
travis-ci-status 1.3.1 
typewriter 0.7.0 
unity-ui 2.1.11 
wakatime 7.0.3 
white-ui 2.6.2 
wraptor 0.2.1 
Writer 0.1.0 
yosemite-unity-ui 0.3.13 
```

**Comment by inkytonik** [comment]
I'm stumped at this point. The line where it dies is the first place we call a method ('add') on the busy signal provider. So it's null for some reason.

Can you please check the console (alt-cmd-i on Mac or "Window: Toggle Dev Tools" command in palette) to see if there are any other messages there?

**Comment by hawkw** [comment]
@inkytonik I'll see what I can do! Sorry I keep re-opening so many issues, and I really appreciate your persistence!

**Comment by inkytonik** [comment]
@hawkw No worries! I'd love to track this down.

**Comment by inkytonik** [comment]
@hawkw Any more information on this issue?

**Comment by hawkw** [comment]
@inkytonik No, sorry! I'm afraid I've mostly switched to using VS Code at this point (mainly due to other, unrelated Atom bugs)...

**Comment by inkytonik** [comment]
No worries. Will close for now. Please reopen if you come back to Atom and still have the problem.
